/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();

        //////////// TESTINGS FOR => role()
        assertEquals(2, classUnderTest.roll(2).length, "Test failed check your parameters");

        //////////// TESTINGS FOR => containsDuplicate()
        assertTrue(classUnderTest.containsDuplicates(new int[]{1, 2, 3, 2}), "Test Failed");

        //////////// TESTINGS FOR => averageCalculator()
        assertEquals(6, classUnderTest.averageCalculator(new int[]{7, 6, 2, 9}));

        //////////// TESTINGS FOR => lowestAverage()
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] arr = new int[]{55, 54, 60, 53, 59, 57, 61};
        assertEquals(Arrays.toString(arr), Arrays.toString(classUnderTest.lowestAverage(weeklyMonthTemperatures)));
    }
}
