/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {

        Restaurant mcDonalds = new Restaurant("Mcdonalds","$");
        Review review1 = new Review("Good fast food","Osaid",3);
        mcDonalds.addReview(review1);
        System.out.println(mcDonalds);

    }
}
