/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {

        Restaurant mcDonalds = new Restaurant("Mcdonalds","$");
        mcDonalds.addReview("Good fast food","Osaid",3);
        mcDonalds.addReview("Bad","Naim",1);
        System.out.println(mcDonalds);

    }
}
