/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void restaurantTesting() {
        Restaurant mcDonalds = new Restaurant("McDonald's", "$$");
        assertNotNull(mcDonalds, "Check your class , it returned NULL");
        assertEquals("McDonald's", mcDonalds.getName());
    }

    @Test
    void reviewTesting() {
        Restaurant mcDonalds = new Restaurant("McDonald's", "$$");
        mcDonalds.addReview("Food was good", "Osaid", 4);


        assertNotNull(mcDonalds, "Check your class , it returned NULL");

        assertEquals("[Reviewer : Osaid\n" +
                "Review : Food was good\n" +
                "Rating :  4 stars\n" +
                "]", mcDonalds.getReviews().toString());

        assertEquals("Please Choose a rating between 0 and 5 stars", mcDonalds.addReview("blah", "bluh", 7));
        assertEquals("Please Choose a rating between 0 and 5 stars", mcDonalds.addReview("blah", "bluh", -5));
    }


}
