/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void restaurantTesting() {
        Restaurant mcDonalds = new Restaurant("McDonald's", "$$");
        assertNotNull(mcDonalds, "Check your class , it returned NULL");
        assertEquals("McDonald's", mcDonalds.getName());
    }

    @Test
    void reviewTesting() {
        Restaurant mcDonalds = new Restaurant("McDonald's", "$$");
        Review review1 = new Review("Food was good","Osaid",4);
        Review review2 = new Review("Blah","Blah",7);
        Review review3 = new Review("Blah","Blah",-4);
        mcDonalds.addReview(review1);


        assertNotNull(mcDonalds, "Check your class , it returned NULL");

        assertEquals("[Reviewer : Osaid\n" +
                "Review : Food was good\n" +
                "Rating :  4 stars\n" +
                "]", mcDonalds.getReviews().toString());

        assertEquals("Please Choose a rating between 0 and 5 stars", mcDonalds.addReview(review2));
        assertEquals("Please Choose a rating between 0 and 5 stars", mcDonalds.addReview(review3));
    }


}
